MyFirstProject/urls.py
from django.contrib import admin
from django.urls import path
from auction.views import main, catolog, items

urlpatterns = [
    path('', main),
    path('catologs/', catolog, name='section'),
    path('<int:dep>/', items, name='lots'),
    path('admin/', admin.site.urls),
]

auction/models.py
from django.db import models

# Create your models here.

class Lot(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    date_open = models.DateTimeField()
    date_close = models.DateTimeField()
    department = models.ForeignKey(
        'Section',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

class Section(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    
    def __str__(self):
        return self.name

auction/views.py
from django.shortcuts import render
from .models import Section, Lot

# Create your views here.
def main(request):
    a = len(Lot.objects.all())
    return render(request, 'index.html', {"a": a})

def catolog(request):
    departments = Section.objects.all().order_by('name')
    return render(request, 'catologs.html', {"departments": departments})

def items(request, dep):
    departments = Section.objects.get(id=dep)
    return render(request, 'department.html', {'dep': departments})

auction/templates/catologs.html
<center>
    <h1> Catologs </h1>
</center>
{% for item in departments %}
    <h2> <a href={% url 'lots' item.id %}> {{item.name}} </a> </h2>
    <h3> {{item.description}} </h3>
    <br> 
{% endfor %}

auction/templates/department.html
<center>
    <h1> Department {{dep}}</h1>
</center>

<h2>
    <ul>
        {% for item in dep.lot_set.all %}
            <li> 
                {{ item.name }}: cost = {{ item.price }}$, date open - {{item.date_open}}, date close - {{item.date_close}} <br>
                {{item.description}}
            </li>
        {% endfor %}
    </ul>
</h2>

auction/templates/index.html
{% load static %}

<center> 
    <h1>AUCTION</h1>
    <image src = "{% static "img/money.jpg" %}" /> <br>
    <h2>
    	Lots = {{a}} <br> <br> <br>
    	<a href="{% url 'section' %}">View catologs</a>
    </h2>
</center>